application: overmind-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: off
- appstats: on
- deferred: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

- name: lxml
  version: latest

- name: PIL
  version: latest


handlers:

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /.*
  script: main.application

